### ISSUE TITLE
Throw in a navigation drawer

### ISSUE THREAD

**Issue by sohayb** [vitovalov/TabbedCoordinatorLayout#1]
Great! was having a hell of a time to make that work, but can you throw an extra navigation drawer to check how that might work?
The tabs should be inside a fragment switched from the drawer.
Thanks

**Comment by hardikamal** [comment]
+1

**Comment by vikmarino** [comment]
Sry, have no time these days

**Comment by tangchao0106** [comment]
复制到我的代码里面来之后,如果只有两个viewpage,设置fill也不起作用..

**Comment by stevyhacker** [comment]
I've done it. Here you can check the implementation. I have also opened a pull request.
https://github.com/stevyhacker/TabbedCoordinatorLayout

**Comment by vikmarino** [comment]
Thanks @stevyhacker. I've accepted your PR #5
